import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';
import en from './locales/en.json';
import hi from './locales/hi.json';
import pa from './locales/pa.json';
import mr from './locales/mr.json';

/**
 * Officials read the console in the same four languages citizens use
 * (PRODUCT_SPEC multilingual rules). en.json is the source; hi/pa/mr are
 * generated by Cloud Translation (`pnpm --filter @vayusetu/gcp-clients
 * translate-locales`) and reviewed -- human edits are never overwritten.
 * Dynamic content (Gemini briefings, advisories) arrives already localized
 * and is rendered as-is.
 */
export const SUPPORTED_LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'pa', label: 'ਪੰਜਾਬੀ' },
  { code: 'mr', label: 'मराठी' },
] as const;

void i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources: {
      en: { translation: en },
      hi: { translation: hi },
      pa: { translation: pa },
      mr: { translation: mr },
    },
    fallbackLng: 'en',
    supportedLngs: ['en', 'hi', 'pa', 'mr'],
    interpolation: { escapeValue: false },
    detection: { order: ['localStorage', 'navigator'], caches: ['localStorage'], lookupLocalStorage: 'vayusetu-admin:lang' },
  });

export default i18n;
